name: Build and deploy Python project to Azure Function App - metrics-functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'metrics-functions'
        package: '.'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_838408DE49ED44CA980581A3A7303D97 }}
        sku: 'flexconsumption'
        remote-build: true
