name: Build and deploy Python project to Azure Function App - metrics-functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          mkdir -p .python_packages/lib/site-packages
          pip install -r requirements.txt --target .python_packages/lib/site-packages

      - name: Upload to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: metrics-functions
          slot-name: Production
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_838408DE49ED44CA980581A3A7303D97 }}
