name: Build and deploy Python project to Azure Function App - metrics-functions

on:
  push:
    branches:
      - main
    paths:
      - 'copilot-metrics-functions/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'metrics-functions'
        package: './copilot-metrics-functions'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        sku: 'flexconsumption'
        remote-build: true
